### ISSUE TITLE
Key bind requests thread

### ISSUE THREAD

**Issue by caleb-allen** [caleb-allen/VimBindings.jl#15]
# Key Bind Request Thread
This thread exists to track any keybind requests. Because of limited development time and resources, it is unlikely that VimBindings.jl will ever be a full implementation.

It is most helpful for me to know what users of VimBindings.jl feel is most lacking, that way I can allocate my time in a way that is most effective for improving the library for the most amount of users.

If there is a keybinding that you'd like to be added to VimBindings.jl, first check to see if it is already in this thread. Add a :+1: if it exists, otherwise write a comment with the keybind request.

- [x] Text movements like `ciw`, `ci"`
- [x] `0` to go to beginning of line
- [x] `$`, `0` - jump to end of line, jump to start of line
- [x] `f` and `F` for text movements
- [ ] `S` to clear the line from anywhere
- [ ] `r` to replace current character
- [ ] `vv` - open current line in your $EDITOR (perhaps this could be implemented with the @edit macro)
- [ ] `r`, `R` - replace, overwrite
- [ ] `u`, `C-r` - undo, redo

**Comment by caleb-allen** [comment]
`0` to go to beginning of line

**Comment by caleb-allen** [comment]
`S` to clear the line from anywhere

(per https://github.com/caleb-allen/VimBindings.jl/issues/14#issuecomment-1009199314)

**Comment by Praful** [comment]
`r` to replace current character would be nice instead of deleting then adding.

Of the binding requests, I miss `0` and `r` most, followed by `S` to clear the line and enter insert mode, in case I decide that edited the current line is more hassle than typing anew.

**Comment by fatteneder** [comment]
Hi,

here is a list of key binds I often use when working with `zsh` and with `vi` mode enabled (`set -o vi`, also works with `bash`):
- `vv` - open current line in your `$EDITOR` (perhaps this could be implemented with the `@edit` macro)
- `r, R` - replace, overwrite
- various text movements (`f, F, t, T`) and manipulations like `ciw, ci"` etc.
- `u, C-r` - undo, redo
- `$, 0` - jump to end of line, jump to start of line

Here is also a link to the default `vi` mode bindings enabled in `zle` as an inspiration or implementation reference: https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Standard-Widgets

**Comment by MilesCranmer** [comment]
I think the text movements `f` and `F` would be very useful (also posted by @fatteneder; I re-posted here so people could 👍 on just these alone)

**Comment by caleb-allen** [comment]
`0` to go to beginning of line solved by #26. Thanks @MilesCranmer!

`$` has also been fixed (among many others).

Both are in `master` and will be available in the next version, `0.1.2`

**Comment by caleb-allen** [comment]
`f` and `F` for text movements is complete! #22

**Comment by caleb-allen** [comment]
I am closing this issue in favor of using an issue for each request. It should make it easier to track and communicate the progress that happens between releases.

I've opened an issue for the keys requested in this thread that are still outstanding and mentioned the requestor in the thread so they can follow progress.

**Comment by jlbosse** [comment]
`o` and `O` to create a new line below or above the current one and go into insert mode.

**Comment by caleb-allen** [comment]
@fatteneder undo and redo with `u` and `C-r` are now implemented and are available in `0.3.4`

**Comment by fatteneder** [comment]
Wow, I had already forgotten about this package.
I just tested it and its amazing :)
Keep up the great work!

**Comment by bjarthur** [comment]
`s` to delete the current character and enter insert mode

**Comment by jlbosse** [comment]
`ci"` and `ci(` to change string contents or function arguments.

`ciw` works as expected, but `ci"` not yet

**Comment by caleb-allen** [comment]
@jlbosse `o` and `O` has been fixed

@bjarthur `s` has been implemented

These are both available in [0.3.7](https://github.com/caleb-allen/VimBindings.jl/releases/tag/v0.3.7)

**Comment by caleb-allen** [comment]
Clipboard integration with `y`, `p`, and `P` has been added in `0.3.8`. It is disabled by default, but can be enabled by running `VimBindings.Config.system_clipboard!(true)`. See the [docs](https://caleb-allen.github.io/VimBindings.jl/v0.3.8/config/#System-Clipboard-Integration) for more details.

It's disabled by default because I haven't been able to test it across platforms. My development machine runs linux and had some unpredictable issues. My guess is that it is more consistent and stable on other operating systems.

For anybody willing to try it out, feel free to give feedback on #7

**Comment by bjarthur** [comment]
`v`
