### ISSUE TITLE
compat issue with Debugger

### ISSUE THREAD

**Issue by ArbitRandomUser** [caleb-allen/VimBindings.jl#16]
might have to bump compat for `Debugger` 
i'm getting this in julia-1.8 
```
ERROR: Unsatisfiable requirements detected for package JuliaInterpreter [aa1ae85d]:
 JuliaInterpreter [aa1ae85d] log:
 ├─possible versions are: 0.1.1-0.9.15 or uninstalled
 ├─restricted by compatibility requirements with Debugger [31a5f54b] to versions: 0.7.0-0.8.21
 │ └─Debugger [31a5f54b] log:
 │   ├─possible versions are: 0.1.0-0.7.6 or uninstalled
 │   └─restricted to versions 0.6 by VimBindings [51b3953f], leaving only versions 0.6.0-0.6.8
 │     └─VimBindings [51b3953f] log:
 │       ├─possible versions are: 0.1.0 or uninstalled
 │       └─VimBindings [51b3953f] is fixed to version 0.1.0
 └─restricted by julia compatibility requirements to versions: 0.9.11-0.9.15 or uninstalled — no versions left
 ```
(not sure if JuliaInterpretter got installed as a dep from one of the packages i installed though)

**Comment by caleb-allen** [comment]
@ArbitRandomUser I've removed the dependency on `Debugger`, you should be able to install without this issue.

I'm closing the issue for now, please re-open if there's still an issue!

**Comment by MilesCranmer** [comment]
@caleb-allen - I think Debugger is still in Project.toml (I'm seeing this issue also).

(Great package btw! You should add it to the package registry)

**Comment by caleb-allen** [comment]
@MilesCranmer you're right, my mistake!

Removed in 248645a92a03eccdbaf9249a75262ae935a72a90

> (Great package btw! You should add it to the package registry)

Thank you! I intend on adding it to the package registry after a few higher priority issues are resolved (e.g. #18)
