### ISSUE TITLE
Forward/backward search with f/F

### ISSUE THREAD

**Issue by MilesCranmer** [caleb-allen/VimBindings.jl#22]
For me the most useful vim commands are `f` and `F` for quickly moving to a specific part of the line. Would be great if these could be added!

**Comment by caleb-allen** [comment]
@MilesCranmer e245867 adds support for `f`, `F`, `t` and `T`!

I'll close this issue once these motion commands work with operators, e.g. `cfx` or `dtf`

**Comment by MilesCranmer** [comment]
Awesome, thanks!
