### ISSUE TITLE
Control + C in normal mode

### ISSUE THREAD

**Issue by mfherbst** [caleb-allen/VimBindings.jl#34]
I think in normal mode Control + C should behave the same as in insert mode (discard the current line of input and bring up a new input line in insert mode.

**Comment by caleb-allen** [comment]
Thanks for the feedback! I think I'll able to include this in the next version

**Comment by caleb-allen** [comment]
This has been added in ddea031b11b6ff315d2f1d05cac5e8713c17f9e0 and will be available in `0.3.0
