### ISSUE TITLE
REPL hangs when trying to delete last line

### ISSUE THREAD

**Issue by ArbitRandomUser** [caleb-allen/VimBindings.jl#84]
steps to reproduce :

open julia REPL with vimbindings.jl

type 2 lines .
```julia-repl
julia> function f()
       end
```

place cursor on `end` in the above , hit `dd` -> line gets removed, 
hit `dd` again -> repl hangs.

**Comment by caleb-allen** [comment]
@ArbitRandomUser 0.3.10 is now available!
